# See https://upptime.js.org/docs/configuration

owner: vojeroen
repo: uptime

sites:
  - name: Nextcloud
    url: $NEXTCLOUD_URL

status-website:
  baseUrl: /uptime
  logoUrl: https://www.acacia0.com/static/acacia0/img/logo-h150.jpg
  name: Acacia0
