# See https://upptime.js.org/docs/configuration

owner: vojeroen
repo: uptime

sites:
  - name: Bitwarden
    url: $URL_BITWARDEN
  - name: Chat (element)
    url: $URL_ELEMENT
  - name: Chat (synapse)
    url: $URL_SYNAPSE
  - name: Git
    url: $URL_GIT
  - name: Home assistant
    url: $URL_HOME_ASSISTANT
  - name: Mail IMAP
    check: "tcp-ping"
    url: $DOMAIN_MAIL_IMAP
    port: 993
  - name: Mail SMTP delivery
    check: "tcp-ping"
    url: $DOMAIN_MAIL_SMTP
    port: 25
  - name: Mail SMTP submission
    check: "tcp-ping"
    url: $DOMAIN_MAIL_SMTP
    port: 587
  - name: Nextcloud
    url: $URL_NEXTCLOUD
  - name: Timetracker
    url: $URL_TIMETRACKER

status-website:
  baseUrl: /uptime
  logoUrl: https://www.acacia0.com/static/acacia0/img/logo-h150.jpg
  name: Acacia0
